.TH SECRET 1 "November 2021"
.SH SECRET
secret \- transfering file from client to client.
.SH SYNOPSIS
.B secret
[\fIOPTIONS\fR]
.SH DESCRIPTION
Transfering file from client to client using ICMP or ICMPv6 packets. 
If the file is greater than a packet size, the file is divided into more packets.
Received files are stored in the current directory. Server support multiple files tranfer sequentially. 
File transfer is stopped when SIGINT (CTRL+C) is recieved. 
Until this evenet the servert is waitng for other file to be recieved.
.SH OPTIONS
.TP
.BR \-r 
File to transfer.
.TP
.BR \-s 
Destination IP address or hostname.
.TP
.BR \-l 
runs as server, which listens for incoming ICMP 
messages and stores them in current directory.
.TP
.BR \-h
Print help menu. 
.SH EXAMPLES
.TP
sudo ./secret -r example_file.txt -s 192.168.0.1
Send file "example_file.txt" to 192.168.0.1
.TP 
sudo ./secret -l
Wait for all files to be recieved.
.SH AUTHOR
.TP 
Written by Michal Findra (xfindr00)

